# ------------------------------------------------------------------------------
# stop.yml
#
# Stop the foo-receive service.
# ------------------------------------------------------------------------------
---
# TODO: Implement the stop.yml task file.
- ansible.builtin.debug:
    msg: '"Stopping foo-receive service"'
- name: Start Service
  shell: '/usr/sbin/service foo-receive stop'
  args:
    executable: /usr/bin/bash
